---
type: cnct
uniqueId: central-management-cluster-config
displayName: central-management-cluster-config Pipeline
description: Configuration for the Hybrid Stack CMC Cluster
apiUrl: "https://api.github.com"
org: samsung-cnct
repo: central-management-cluster-config
keepDays: 10
credentials: github-access